package org.logstash.secret.store;

import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Base64;
import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;

public class SecretStoreUtil {

    public static byte[] base64encode(String s) {
        byte[] bytes = Base64.getEncoder().encode(s.getBytes(StandardCharsets.UTF_8));
        //a poor attempt to clear the String from memory
        s = null;
        System.gc();
        return bytes;
    }

    public static byte[] base64Decode(byte[] b) {
        byte[] bytes = Base64.getDecoder().decode(b);
        clear(b);
        return bytes;
    }


    public static char[] obfuscate(String s){
        return obfuscate(asciiBytesToChar(base64encode(s)));
    }
    /**
     * Converts bytes from ascii encoded text to a char[] and zero outs the original byte[]
     *
     * @param bytes the bytes from an ascii encoded text (note - no validation is done to ensure ascii encoding)
     * @return the corresponding char[]
     */
    public static char[] asciiBytesToChar(byte[] bytes) {
        char[] chars = new char[bytes.length];
        for (int i = 0; i < bytes.length; i++) {
            chars[i] = (char) bytes[i];
            bytes[i] = '\0';
        }
        return chars;
    }

    /**
     * Converts characters from ascii encoded text to a byte[] and zero outs the original char[]
     *
     * @param chars the chars from an ascii encoded text (note - no validation is done to ensure ascii encoding)
     * @return the corresponding byte[]
     */
    public static byte[] asciiCharToBytes(char[] chars) {
        byte[] bytes = new byte[chars.length];
        for (int i = 0; i < chars.length; i++) {
            bytes[i] = (byte) chars[i];
            chars[i] = '\0';
        }
        return bytes;
    }

    /**
     * Attempt to keep data out of the heap.
     *
     * @param bytes the bytes to zero out
     */
    public static void clear(byte[] bytes) {
        for (int i = 0; i < bytes.length; i++) {
            bytes[i] = '\0';
        }
        bytes = null;
    }

    /**
     * Simple obfuscation that adds a bit of randomness and shuffles the bits of a char[]. Note - this is NOT security, will only deter the lazy, and is admittedly kinda silly.
     *
     * @param chars The chars to obscure
     * @return the obscured bytes
     */
    public static char[] obfuscate(char[] chars) {
        byte[] bytes = asciiCharToBytes(chars);
        byte[] random = new byte[bytes.length];
        new Random().nextBytes(random);
        //TODO get of byte buffer and work with arrays directly
        ByteBuffer obfuscated = ByteBuffer.allocate(bytes.length * 2);
        for (int i = 0; i < bytes.length; i++) {
            int xor = bytes[i] ^ random[i];
            obfuscated.put((byte) (0xff & xor));
        }
        //TODO: clear arrays
        obfuscated.put(random);
        return asciiBytesToChar(obfuscated.array());
    }

    /**
     * De-obfuscates the obfuscated char[] generated by {@link SecretStoreUtil#obfuscate(char[])}
     *
     * @param chars The chars to de-obscure
     * @return the de-obscured chars
     */
    public static char[] deObfuscate(char[] chars) {
        byte[] bytes = asciiCharToBytes(chars);
        byte[] random = Arrays.copyOfRange(bytes, bytes.length / 2, bytes.length);
        byte[] deObfuscated = new byte[random.length];
        for (int i = 0; i < random.length; i++) {
            int xor = bytes[i] ^ random[i];
            deObfuscated[i] = ((byte) (xor & 0xff));
        }
        return asciiBytesToChar(deObfuscated);
    }
}
