package org.logstash.secret.store;

import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.Base64;
import java.util.Random;

/**
 * Conversion utility between String, bytes, and chars. All methods attempt to keep sensitive data out of memory. Sensitive data should avoid using Java {@link String}'s.
 */
final public class SecretStoreUtil {

    /**
     * Private constructor. Utility class.
     */
    private SecretStoreUtil() {
    }

    /**
     * Converts bytes from ascii encoded text to a char[] and zero outs the original byte[]
     *
     * @param bytes the bytes from an ascii encoded text (note - no validation is done to ensure ascii encoding)
     * @return the corresponding char[]
     */
    public static char[] asciiBytesToChar(byte[] bytes) {
        char[] chars = new char[bytes.length];
        for (int i = 0; i < bytes.length; i++) {
            chars[i] = (char) bytes[i];
            bytes[i] = '\0';
        }
        return chars;
    }

    /**
     * Converts characters from ascii encoded text to a byte[] and zero outs the original char[]
     *
     * @param chars the chars from an ascii encoded text (note - no validation is done to ensure ascii encoding)
     * @return the corresponding byte[]
     */
    public static byte[] asciiCharToBytes(char[] chars) {
        byte[] bytes = new byte[chars.length];
        for (int i = 0; i < chars.length; i++) {
            bytes[i] = (byte) chars[i];
            chars[i] = '\0';
        }
        return bytes;
    }



    public static byte[] base64Encode(byte[] b) {
        byte[] bytes = Base64.getEncoder().encode(b);
        clearBytes(b);
        return bytes;
    }

    public static char[] base64encode(char[] chars) {
        return asciiBytesToChar(base64Encode(asciiCharToBytes(chars)));
    }

    /**
     * Attempt to keep data out of the heap.
     *
     * @param bytes the bytes to zero out
     */
    public static void clearBytes(byte[] bytes) {
        for (int i = 0; i < bytes.length; i++) {
            bytes[i] = '\0';
        }
        bytes = null;
    }

    /**
     * Attempt to keep data out of the heap.
     *
     * @param chars the chars to zero out
     */
    public static void clearChars(char[] chars) {
        for (int i = 0; i < chars.length; i++) {
            chars[i] = '\0';
        }
        chars = null;
    }

    /**
     * De-obfuscates the obfuscated char[] generated by {@link SecretStoreUtil#obfuscate(char[])}
     *
     * @param chars The chars to de-obscure
     * @return the de-obscured chars
     */
    public static char[] deObfuscate(char[] chars) {
        byte[] bytes = asciiCharToBytes(chars);
        byte[] random = Arrays.copyOfRange(bytes, bytes.length / 2, bytes.length);
        byte[] deObfuscated = new byte[random.length];
        for (int i = 0; i < random.length; i++) {
            int xor = bytes[i] ^ random[i];
            deObfuscated[i] = ((byte) (xor & 0xff));
        }
        return asciiBytesToChar(deObfuscated);
    }

    /**
     * <p>Simple obfuscation that adds a bit of randomness and shuffles the bits of a char[].</p>
     * <p>Note - this is NOT security and will only deter the lazy.</p>
     *
     * @param chars The chars to obscure
     * @return the obscured bytes
     */
    public static char[] obfuscate(char[] chars) {
        byte[] bytes = asciiCharToBytes(chars);
        byte[] random = new byte[bytes.length];
        new Random().nextBytes(random);

        ByteBuffer obfuscated = ByteBuffer.allocate(bytes.length * 2);
        for (int i = 0; i < bytes.length; i++) {
            int xor = bytes[i] ^ random[i];
            obfuscated.put((byte) (0xff & xor));
        }
        obfuscated.put(random);
        char[] result = asciiBytesToChar(obfuscated.array());
        clearBytes(obfuscated.array());
        return result;
    }
}
