# This file is generated by Gradle as part of the build process. It extracts the build.gradle
# runtime dependencies to generate this gemspec dependencies file to be eval'ed by the gemspec
# for the jar-dependencies requirements.

gem.requirements << "jar org.apache.logging.log4j:log4j-slf4j-impl, 2.6.2"
gem.requirements << "jar org.apache.logging.log4j:log4j-api, 2.6.2"
gem.requirements << "jar org.apache.logging.log4j:log4j-core, 2.6.2"
gem.requirements << "jar com.fasterxml.jackson.core:jackson-core, 2.7.3"
gem.requirements << "jar com.fasterxml.jackson.core:jackson-databind, 2.7.3"
gem.requirements << "jar com.fasterxml.jackson.core:jackson-annotations, 2.7.3"
gem.requirements << "jar com.fasterxml.jackson.module:jackson-module-afterburner, 2.7.3"
gem.requirements << "jar com.fasterxml.jackson.dataformat:jackson-dataformat-cbor, 2.7.3"
gem.requirements << "jar org.eclipse.jetty:jetty-servlet, 9.4.6.v20170531"
gem.requirements << "jar org.eclipse.jetty:jetty-server, 9.4.6.v20170531"
gem.requirements << "jar org.eclipse.jetty:jetty-util, 9.4.6.v20170531"
gem.requirements << "jar org.glassfish.jersey.core:jersey-server, 2.25.1"
gem.requirements << "jar org.glassfish.jersey.containers:jersey-container-servlet-core, 2.25.1"
gem.requirements << "jar org.glassfish.jersey.containers:jersey-container-jetty-http, 2.25.1"
gem.requirements << "jar org.glassfish.jersey.media:jersey-media-json-jackson, 2.25.1"
